### ISSUE TITLE
Release 2.0.3

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/wait-for#141]
I think that a new release is needed so that the published docker image has the latest Alpine CVE fixes etc.

https://github.com/owncloud-ci/wait-for/releases

That has been done by "ownclouders" and renovate bot. How do we trigger that to happen?

@micbar or @deepdiver do you know how this works?

**Comment by micbar** [comment]
Latest has been published today. I merged the renovate PRs 3 hours ago.

**Comment by phil-davis** [comment]
What is the use of the https://github.com/owncloud-ci/wait-for/releases ?

https://github.com/owncloud-docker/ubuntu/blob/master/v20.04/Dockerfile.multiarch#L20 has
```
ENV WAIT_FOR_VERSION="${WAIT_FOR_VERSION:-v2.0.2}"
```

Does v2.0.3 need to happen somehow?

**Comment by phil-davis** [comment]
@micbar are there supposed to be release tags?
And are we supposed to be using them?
Or should we pin to an SHA from other repos that use wait-for?
What is the workflow supposed to be?

**Comment by micbar** [comment]
I don’t know. Let us find out. You can just tag.

**Comment by phil-davis** [comment]
I see that "ownclouders" made the tags and releases. I wonder how that happened?

**Comment by phil-davis** [comment]
> Could be the CI creating the release in gh.

Good idea - there is drone CI code that triggers on tag. I did:
```
git fetch origin
git checkout master
git pull
git tag v2.0.3
git push origin tag v2.0.3
```

And drone ran off the tag, and it made https://github.com/owncloud-ci/wait-for/releases/tag/v2.0.3
